#!/usr/bin/env Rscript
prompt1 <- "Are you running local test or uploading your platform to a server? (local/server)"
prompt2 <- "Please type the length of your questionnaire "

cat(prompt1)
position <- readLines("stdin", n = 1)

cat(prompt2)
qlen <- readLines("stdin", n = 1) |> as.integer()

cat ("Arguments accepted, inatialising ......")

readRenviron(".env")
env_dbname <- Sys.getenv('DB_NAME')
env_port <- Sys.getenv('SQL_PORT')
env_password <- Sys.getenv('DB_PASS')
env_usr <- Sys.getenv('USR_NAME')

if (position == "local") {
  env_server <- '127.0.0.1'
  source ("R/init_db.R")
} else if (position == "server") {
  env_server <- Sys.getenv ('SERVER_NAME')
} else {
  stop ('arguments must be either "local" or "server"')
}

source ("R/init_table.R")
source ("R/init_trial.R")
source ("R/insertProc.R")
source ("R/db_conf.R")

cat("DONE")
