#!/usr/bin/env Rscript
prompt1 <- "Are you running local test or uploading your platform to a server? (local/server) "
prompt2 <- "The name of target questionnaire you would like to use, extension required: "

cat(prompt1)
position <- readLines("stdin", n = 1)

cat (prompt2)
quest_name <- readLines("stdin", n = 1)

source ("R/make_scale.R")

cat ("Questionnaire has parsed and saved to `www` \n")

qlen <- nrow (quest)
cat ("Reading evnironment configuration... \n")

if (file.exists("/.dockerenv")) {
  readRenviron("server.env")
} else {
  readRenviron(".env")
}
env_port <- Sys.getenv('SQL_PORT')
env_password <- Sys.getenv('DB_PASS')
env_usr <- Sys.getenv('USR_NAME')
env_quest <- quest_name

cat ("Arguments accepted, inatialising ...... \n")

if (position == "local") {
  sql_dbname <- tools::file_path_sans_ext (quest_name)
  if (file.exists ("/.dockerenv")) {
    env_server <- "host.docker.internal"
  } else {
    env_server <- "127.0.0.1"
  }
  source ("R/init_db.R")
} else if (position == "server") {
  env_server <- Sys.getenv('SERVER_NAME')
  sql_dbname <- Sys.getenv('SERVER_DB_NAME')
} else {
  stop ('arguments must be either "local" or "server"')
}
source ("R/init_table.R")
source ("R/init_trial.R")
source ("R/insertProc.R")
source ("R/db_conf.R")

cat("Initialization done")
